print("#############################")
print("#                           #")
print("#    NADYA NADHIR SORAYA    #")
print("#       2510817120022       #")
print("#                           #")
print("#############################")